### PR TITLE
Install desktop, svg and metainfo files with pybuild

### PR DESCRIPTION
**Pull request by marillat**
This pr fix issue #83

### CODE REVIEW

**Comment by cydanil** [comment]
Thank you!  
Do you know how well this works for other operating systems?

**Comment by marillat** [comment]
I don't know as I'm a Linux user. I don't know how python is supposed to work with Windows.

**Comment by marillat** [comment]
It is possible to ass more build tests ?
For now only a build test for ubuntu  20.04 is available.

**Comment by cydanil** [comment]
I am all for it. Ubuntu 20.04 was chosen as the LTS at that time.  
We should add Ubuntu 22.04 which is now available.

**Comment by marillat** [comment]
I was talking about windows.

**Comment by cydanil** [comment]
I see.  
Yes, it would be beneficial. However, getting Gourmand to work on windows is a bit artisanal at the moment, as packaging Gtk seems involved and I don't have a Windows computer to develop with.  
At the moment, I'd rather work on stabilizing Gourmand before looking at that.  
Nonetheless, I asked for infos because I would like to avoid adding os-dependent limitations.  

This MR is generally LGTM, but I haven't had the time to test it yet, hence why it's not merged yet :slightly_smiling_face:

**Comment by cydanil** [comment]
This works nicely on Ubuntu 20.04.  
Thanks for your help!

**Pull request merged**
