### PR TITLE
Fix for forksoverknives.com recipes

### PR DESCRIPTION
**Pull request by manithree**
Some, at least return yields like: "2 to 4"
This may not be the correct way to fix that, but it lets me import more fok recipes

## Description

Some (many?) FOK yields are free-form, and would throw an exception, and the recipe would not get imported.

## How Has This Been Tested?

The 3-4 samples I tried now successfully import

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by cydanil** [comment]
Thanks @manithree  
This is certainly one way to do it.  
Could you explicitly catch the exceptions rather than having a bare `except:`?  
Could you also give me one of these FOK recipes that used to fail the import?  

Cheers,  
Cyril

**Comment by manithree** [comment]
https://www.forksoverknives.com/recipes/vegan-burgers-wraps/sweet-potato-and-veggie-roll-ups/
File "/home/blr/Downloads/build/gmd-venv/lib/python3.10/site-packages/recipe_scrapers/forksoverknives.py", line 23, in yields
    self.soup.find("i", attrs={"class": "icon-serving"}).next_sibling.get_text()
AttributeError: 'NoneType' object has no attribute 'next_sibling'

https://www.forksoverknives.com/recipes/vegan-soups-stews/curried-butternut-squash-and-cauliflower-stew/
  File "/home/blr/Downloads/build/gourmand/src/gourmand/importers/web_importer.py", line 79, in import_urls
    yields, yield_unit = recipe.yields().split()
ValueError: too many values to unpack (expected 2)

I'm pretty sure I gave up after 3 distinct errors, but I can't seem to find the third one atm. recipe-scrapers is not using the schema for forksoverknives, and I plan to submit a patch to fix that. I believe that could help with the first one, but probably not the the second one.

**Comment by FriedrichFroebel** [comment]
@manithree Are you still interested in updating the PR as requested?

**Comment by manithree** [comment]
> @manithree Are you still interested in updating the PR as requested?

It appears this is not an acceptable way to fix this issue, and is unlikely to get merged, so, no, I have no interest in updating the PR. I'm fine running my hacked version of gourmand until someone more immersed in the code comes up with a less bad solution. Or forever, since apparently I'm the only person who has this problem.

**Comment by FriedrichFroebel** [comment]
I just had a look at this with the latest *main* code of Gourmand: We now get

```
  File "/home/me/gourmand/venv/lib/python3.12/site-packages/recipe_scrapers/forksoverknives.py", line 56, in ratings
    .find("span", attrs={"class": "rated-count"})
     ^^^^
AttributeError: 'NoneType' object has no attribute 'find'
```

for both recipes you mention when doing `recipe.ratings()`. Thus it does not look like an issue on our side.

**Pull request closed without merging**
